version: "3.7"

networks:
  request-counter-net:
    name: request-counter-net
    driver: bridge

services:
  redis_db:
    container_name: redis-counter
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis_db_v:/data
    networks:
      - request-counter-net

  request-counter-8080:
    build:
      dockerfile: Dockerfile
    image: request-counter:latest
    container_name: request-counter-8080-app
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      REDIS_DB_HOST: redis_db
      REDIS_DB_PORT: 6379
    restart: always
    networks:
      - request-counter-net

  request-counter-8081:
    build:
      dockerfile: Dockerfile
    image: request-counter:latest
    container_name: request-counter-8081-app
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      REDIS_DB_HOST: redis_db
      REDIS_DB_PORT: 6379
    restart: always
    networks:
      - request-counter-net

  request-counter-8082:
    build:
      dockerfile: Dockerfile
    image: request-counter:latest
    container_name: request-counter-8082-app
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      REDIS_DB_HOST: redis_db
      REDIS_DB_PORT: 6379
    restart: always
    networks:
      - request-counter-net
volumes:
  redis_db_v: