version: "3.7"

networks:
  request-counter-net:
    name: request-counter-net
    driver: bridge

services:

  request-counter-8080:
    build:
      dockerfile: Dockerfile
    image: request-counter:latest
    container_name: request-counter-8080-app
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
    restart: always
    networks:
      - request-counter-net

  request-counter-8081:
    build:
      dockerfile: Dockerfile
    image: request-counter:latest
    container_name: request-counter-8081-app
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
    restart: always
    networks:
      - request-counter-net

  request-counter-8082:
    build:
      dockerfile: Dockerfile
    image: request-counter:latest
    container_name: request-counter-8082-app
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
    restart: always
    networks:
      - request-counter-net